# Generated by Django 5.0.2 on 2024-02-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
