# Generated by Django 5.0.2 on 2024-02-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comments_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment_counter',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
